services:
    frenet_sim: 
        image: melodic_baseline:latest 
        stdin_open: true
        tty: true
        build: .
        user: agv
        privileged: true
        environment: 
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./src:/home/agv/frenet_ws/src
        network_mode: host
